spring:
  application:
    name: mscartoes
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}

mq:
  queues:
    emissao-cartoes: emissao-cartoes

server:
  port: ${SERVER_PORT:0} # gera uma porta randomica

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_USER:cursoms-eureka-user}:${EUREKA_PASSWORD:Sv67L8usSiKhl0ek7Xjuq5o6}@${EUREKA_HOST:cursoms-network}:${EUREKA_PORT:8761}/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "*"